//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perspective.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int TraderId { get; set; }

        [Range(0, 2000000000)]
        [DataType(DataType.Currency)]
        [Required]
        public decimal Receivable { get; set; }

        [Range(0, 2000000000)]
        [DataType(DataType.Currency)]
        [Required]
        public decimal Payable { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public System.DateTime Date { get; set; }

        [StringLength(500, MinimumLength = 2)]
        [Required]
        public string Description { get; set; }

        public virtual Trader Trader { get; set; }
    }
}
